title: <p align="center"> Andrea Cusi</p>

logo: "Fototessera2019low-modified.png?raw=true"

description:
  <p align="center">
  <a href="https://www.linkedin.com/in/andrea-cusi-6a24b788">LinkedIn</a> |
  <a href="https://github.com/cusiandrea">GitHub</a>
  </p>
  
  <p align="justify">
  I am an aspiring Data Scientist, passionate about finding answers hidden in data.
  <br><br>
  </p>
  
remote_theme: pages-themes/minimal@v0.2.0
