title: <p align="center"> Andrea Cusi</p>

logo: "Fototessera2019low-modified.png?raw=true"

description:
  <p align="center">
  <a href="https://www.linkedin.com/in/andrea-cusi-6a24b788" target="_blank">LinkedIn</a> |
  <a href="https://github.com/cusiandrea" target="_blank">GitHub</a>
  </p>
  
  <p align="justify">
  Data Scientist turning raw data into clear, actionable stories.
  <br><br>
  </p>
  
remote_theme: pages-themes/minimal@v0.2.0
